In [1]:
%whos

Interactive namespace is empty.


In [1]:
# initialize 
# to initialize displaying webpages within the notebook
from IPython.display import IFrame
# to initialize sympy from ipython:
from sympy import init_session
init_session()
# to initialize sympy from the bash shell:
# isympy

IPython console for SymPy 1.13.3 (Python 3.13.2-64-bit) (ground types: python)

These commands were executed:
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.13.3/



In [2]:
colV = Matrix([x, y])
rowV = Matrix([z, t]).T
colV @ rowV

In [3]:
import numpy as np
import pickle

In [4]:
from IPython.display import Image
Image("images/trask_traffic_light_network_lin_alg_obj.jpg", width=300)

<p>traffic lights neural network laid out as linear algebra objects: matrix, vectors, and scalar.</p>
<p>from: <i><b style='color:red;'>grokking</b> <b>Deep Learning</b></i></p>
<p>by Andrew W. Trask</p>

In [2]:
def relu(x):
    ''' Returns x iff x > 0; otherwise, returns 0
        activation function, nonlinear
    '''
    return (x > 0) * x

In [4]:
import pickle
# unpickle weights_0_1, weights_1_2
with open('pickle/weights_0_1.pickle.bin', 'rb') as in_file:
    weights_0_1 = pickle.load(in_file)
with open('pickle/weights_1_2.pickle.bin', 'rb') as in_file:
    weights_1_2 = pickle.load(in_file)

In [5]:
%whos

Variable      Type              Data/Info
-----------------------------------------
in_file       BufferedReader    <_io.BufferedReader name=<...>/weights_1_2.pickle.bin'>
pickle        module            <module 'pickle' from '/h<...>ib/python3.13/pickle.py'>
relu          function          <function relu at 0x7c8a3c55d620>
weights_0_1   ndarray           3x4: 12 elems, type `float64`, 96 bytes
weights_1_2   ndarray           4x1: 4 elems, type `float64`, 32 bytes


In [7]:
import numpy as np
layer_0 = [0, 1, 1] # enter your input
layer_1 = relu(np.dot(layer_0, weights_0_1)) 
layer_2 = np.dot(layer_1, weights_1_2)
print(int(layer_2[0]))

0


In [14]:
# friendly reminder
# a fast way to hand-enter a matrix
streetlights = np.array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1]).reshape(4, 3)
print(streetlights)
# how to render a column vector
walk_v_stop = np.array([1, 1, 0, 0]).T
print(walk_v_stop)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]
[1 1 0 0]
